SyntaxError: invalid syntax (Temp/ipykernel_17404/283831030.py, line 1)

In [2]:
w, h = 8, 5
Matrix = [[0 for x in range(w)] for y in range(h)] 


In [3]:
Matrix


[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0]]

In [4]:
Matrix[0][6] = 3

In [5]:
Matrix

[[0, 0, 0, 0, 0, 0, 3, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0]]

In [76]:
import numpy as np
def SubsetSum(arr, num):
    #Buat matriks 2 dimensi untuk menyimpan True/False 
    baris = len(arr)+1
    kolom = num+1
    arr2d=numpy.zeros((baris,kolom))
    # Inisiasi kolom pertama adalah 1
    for i in range(baris):
        arr2d[i][0] = 1
    # inisiasi baris pertama adalah 0
    for i in range(1,kolom):
        arr2d[0][i] = 0
    # Lakukan looping untuk pengecekan apakah nilai tersebut nilai yang ada di kolom
    for i in range(1,baris):
        for j in range(1,kolom):
            arr2d[i][j]=arr2d[i-1][j]
            if arr2d[i][j] == False and j>= arr[i-1]:
                arr2d[i][j] = arr2d[i][j] or arr2d[i-1][j-arr[i-1]]
                print("baris ke", i,j)
                print(arr2d)
   # Return True kalau terdapat subset yang berjumlah num dengan cara melihat baris paling akhir dan kolom paling akhir
    return arr2d[baris-1][kolom-1]
# source: https://www.youtube.com/watch?v=34l1kTIQCIA
#source: https://www.youtube.com/watch?v=5td2QH-x5ck

In [78]:
SubsetSum([2,2,3], 6)

baris ke 1 2
[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
baris ke 1 3
[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
baris ke 1 4
[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
baris ke 1 5
[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
baris ke 1 6
[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
baris ke 2 3
[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
baris ke 2 4
[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
baris ke 2 5
[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
baris ke 2 6
[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
baris ke 3

0.0

In [61]:
import numpy
numpy.ones((5, 10)) 

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# Knapsack


In [136]:
import numpy as np
def knapsack(weight_arr,profit_arr,max_weight):
    # buat array 2D untuk menyimpan hasil penghitungan
    baris = len(weight_arr)+1
    kolom = max_weight+1
    arrV = numpy.zeros((baris,kolom))
    # sisipkan elemen 0  di array weight dan array profit supaya mudah saat penghitungan di dalam array 2d
    weight_arr.insert(0,0) 
    profit_arr.insert(0,0)
    
    #lakukan looping pada array 2D untuk memulai mencari profit tertinggi dengan weight<=max weight
    #looping dilakukan dari 1 supaya baris dan kolom ke-0 cukup diisi dengan 0
    for i in range(1,baris):
        for j in range(1,kolom):
            # jika j-weight_arr[i]<0 maka saat pengambilan elemen arrV akan index out of bound 
            # maka dari itu isi value arrV[i,j] dengan elemen tepat 1 baris diatasnya 
            if j-weight_arr[i]<0:
                arrV[i][j] = arrV[i-1][j]
            else:
                #cari value mana yang mengandung profit paling maks antara elemen tepat satu baris diatasnya
                #dengan elemen satu baris di atasnya namun kolomnya digeser kekiri sebesar weight yang dimiliki 
                #dan dijumlahkan profit yang dimiliki
                arrV[i][j] = max(arrV[i-1][j], arrV[i-1][j-weight_arr[i]]+profit_arr[i])
            print("baris ke", i,j)
            print(arrV)
    # Jika sudah selesai kita lihat baris paling akhir dan kolom paling akhir
    # maka itulah profit maksimal dengan weight<=max_weight       
    return arrV[baris-1][kolom-1]
    

In [137]:
knapsack([2,3,4,5],[1,2,5,6],8)

0.0
1
1.0
baris ke 1 1
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
0.0
1
1.0
baris ke 1 2
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
0.0
1
1.0
baris ke 1 3
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
0.0
1
1.0
baris ke 1 4
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
0.0
1
1.0
baris ke 1 5
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
0.0
1
1.0
baris ke 1 6
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 

8.0

In [140]:
knapsack([2,3,5,7,1,4,1],[10,5,15,7,6,18,3],30)

0.0
10
10.0
baris ke 1 1
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]]
0.0
10
10.0
baris ke 1 2
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.  0.  0.  0.  0

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
  10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [ 0.  0. 10. 10. 10. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.
  15. 15. 15.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  

baris ke 4 9
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
  10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [ 0.  0. 10. 10. 10. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.
  15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.]
 [ 0.  0. 10. 10. 10. 15. 15. 25. 25. 25. 30. 30. 30. 30. 30. 30. 30. 30.
  30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30.]
 [ 0.  0. 10. 10. 10. 15. 15. 25. 25. 25.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0. 

   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
31.0
18
49.0
baris ke 6 12
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
  10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [ 0.  0. 10. 10. 10. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.
  15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.]
 [ 0.  0. 10. 10. 10. 15. 15. 25. 25. 25. 30. 30. 30. 30. 30. 30. 30. 30.
  30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30.]
 [ 0.  0. 10. 10. 10. 15. 15. 25. 25. 25. 30. 30. 30. 30. 32. 32. 32. 37.
  37. 37. 37. 37. 37. 37. 37. 37. 37. 37. 37. 37. 37.]
 [ 0.  6. 10. 16. 16. 16. 21. 25. 31. 31. 31. 36. 36. 36. 36. 38. 38. 38.
  43. 43. 43. 43. 43. 43. 43. 43. 43. 43. 43. 43. 43.]
 [ 0.  6. 10. 16. 18. 24. 28. 34. 34. 34. 39. 43. 49.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 

baris ke 7 29
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
  10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [ 0.  0. 10. 10. 10. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.
  15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.]
 [ 0.  0. 10. 10. 10. 15. 15. 25. 25. 25. 30. 30. 30. 30. 30. 30. 30. 30.
  30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30.]
 [ 0.  0. 10. 10. 10. 15. 15. 25. 25. 25. 30. 30. 30. 30. 32. 32. 32. 37.
  37. 37. 37. 37. 37. 37. 37. 37. 37. 37. 37. 37. 37.]
 [ 0.  6. 10. 16. 16. 16. 21. 25. 31. 31. 31. 36. 36. 36. 36. 38. 38. 38.
  43. 43. 43. 43. 43. 43. 43. 43. 43. 43. 43. 43. 43.]
 [ 0.  6. 10. 16. 18. 24. 28. 34. 34. 34. 39. 43. 49. 49. 49. 54. 54. 54.
  54. 56. 56. 56. 61. 61. 61. 61. 61. 61. 61. 61. 61.]
 [ 0.  6. 10. 16. 19. 24. 28. 34. 37. 37. 39. 43. 49. 52. 52. 54. 57. 57.
  57. 57.

64.0

In [128]:
arr

[10, 1, 2, 3, 4, 5, 6]